// -*- C++ -*-
//
// ======================================================================
//
//                           Brad T. Aagaard
//                        U.S. Geological Survey
//
// {LicenseText}
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application simpledbdataarea3D.

#if !defined(spatialdata_spatialdb_simpledbdataarea3d_hh)
#define spatialdata_spatialdb_simpledbdataarea3d_hh

#include "SimpleDBData.hh"

namespace spatialdata {
  namespace spatialdb {
     class SimpleDBDataArea3D;
  } // spatialdata
} // spatialdb

class spatialdata::spatialdb::SimpleDBDataArea3D : public SimpleDBData
{

public: 

  /// Constructor
  SimpleDBDataArea3D(void);

  /// Destructor
  ~SimpleDBDataArea3D(void);

private:

  static const int _numLocs;

  static const int _spaceDim;

  static const int _numVals;

  static const int _dataDim;

  static const int _numQueries;

  static const double _dbData[];

  static const char* _names[];

  static const char* _units[];

  static const double _queryNearest[];

  static const double _queryLinear[];

  static const int _errFlags[];

};

#endif // spatialdata_spatialdb_simpledbdataarea3d_hh

// End of file
