// -*- C++ -*-
//
// ======================================================================
//
//                           Brad T. Aagaard
//                        U.S. Geological Survey
//
// {LicenseText}
//
// ======================================================================
//

// DO NOT EDIT THIS FILE
// This file was generated from python application simpledbdataline3D.

#include "SimpleDBTestDataLine3D.hh"

const int spatialdata::spatialdb::SimpleDBTestDataLine3D::_numLocs = 5;

const int spatialdata::spatialdb::SimpleDBTestDataLine3D::_spaceDim = 3;

const int spatialdata::spatialdb::SimpleDBTestDataLine3D::_numVals = 2;

const int spatialdata::spatialdb::SimpleDBTestDataLine3D::_dataDim = 1;

const int spatialdata::spatialdb::SimpleDBTestDataLine3D::_numQueries = 4;

const double spatialdata::spatialdb::SimpleDBTestDataLine3D::_dbCoords[] = {
  3.40000000e+00,  9.50000000e+00,  8.70000000e+00,
  5.70000000e+00,  9.90000000e+00,  1.85000000e+01,
  6.85000000e+00,  1.01000000e+01,  2.34000000e+01,
  8.00000000e+00,  1.03000000e+01,  2.83000000e+01,
  1.49000000e+01,  1.15000000e+01,  5.77000000e+01,
};

const double spatialdata::spatialdb::SimpleDBTestDataLine3D::_dbData[] = {
  1.00000000e-01,  1.10000000e+00,
  3.00000000e-01,  3.30000000e+00,
  2.00000000e-01,  2.20000000e+00,
  1.00000000e-01,  1.10000000e+00,
 -4.00000000e-01, -4.40000000e+00,
};

const char* spatialdata::spatialdb::SimpleDBTestDataLine3D::_names[] = {
"One",
"Two",
};

const char* spatialdata::spatialdb::SimpleDBTestDataLine3D::_units[] = {
"m",
"m",
};

const double spatialdata::spatialdb::SimpleDBTestDataLine3D::_queryNearest[] = {
  5.70000000e+00,  9.90000000e+00,  1.85000000e+01,  3.00000000e-01,  3.30000000e+00,
  1.26000000e+01,  1.11000000e+01,  4.79000000e+01, -4.00000000e-01, -4.40000000e+00,
  1.72000000e+01,  1.19000000e+01,  6.75000000e+01, -4.00000000e-01, -4.40000000e+00,
  6.16000000e+00,  9.98000000e+00,  2.04600000e+01,  3.00000000e-01,  3.30000000e+00,
};

const double spatialdata::spatialdb::SimpleDBTestDataLine3D::_queryLinear[] = {
  5.70000000e+00,  9.90000000e+00,  1.85000000e+01,  3.00000000e-01,  3.30000000e+00,
  1.26000000e+01,  1.11000000e+01,  4.79000000e+01, -2.33333333e-01, -2.56666667e+00,
  1.72000000e+01,  1.19000000e+01,  6.75000000e+01,  0.00000000e+00,  0.00000000e+00,
  6.16000000e+00,  9.98000000e+00,  2.04600000e+01,  2.60000000e-01,  2.86000000e+00,
};

const int spatialdata::spatialdb::SimpleDBTestDataLine3D::_errFlags[] = {
 0, 0, 1, 0,};

spatialdata::spatialdb::SimpleDBTestDataLine3D::SimpleDBTestDataLine3D(void)
{ // constructor
  numLocs = _numLocs;
  spaceDim = _spaceDim;
  numVals = _numVals;
  dataDim = _dataDim;
  numQueries = _numQueries;
  dbCoords = const_cast<double*>(_dbCoords);
  dbData = const_cast<double*>(_dbData);
  names = const_cast<char**>(_names);
  units = const_cast<char**>(_units);
  queryNearest = const_cast<double*>(_queryNearest);
  queryLinear = const_cast<double*>(_queryLinear);
  errFlags = const_cast<int*>(_errFlags);
} // constructor

spatialdata::spatialdb::SimpleDBTestDataLine3D::~SimpleDBTestDataLine3D(void)
{}


// End of file
