// -*- C++ -*-
//
// ----------------------------------------------------------------------
//
// Brad T. Aagaard, U.S. Geological Survey
//
// This code was developed as part of the Computational Infrastructure
// for Geodynamics (http://geodynamics.org).
//
// Copyright (c) 2010-2016 University of California, Davis
//
// See COPYING for license information.
//
// ----------------------------------------------------------------------
//

// DO NOT EDIT THIS FILE
// This file was generated from python application simpledbquerydata3d.

#if !defined(spatialdata_spatialdb_simpledbquerydata3d_hh)
#define spatialdata_spatialdb_simpledbquerydata3d_hh

#include "SimpleDBQueryData.hh"

namespace spatialdata {
  namespace spatialdb {
     class SimpleDBQueryData3D;
  } // spatialdata
} // spatialdb

class spatialdata::spatialdb::SimpleDBQueryData3D : public SimpleDBQueryData
{

public: 

  /// Constructor
  SimpleDBQueryData3D(void);

  /// Destructor
  ~SimpleDBQueryData3D(void);

private:

  static const int _numLocs;

  static const int _spaceDim;

  static const int _numVals;

  static const int _dataDim;

  static const int _numPts;

  static const double _dist2;

  static const double _area;

  static const double _volume;

  static const double _dbCoords[];

  static const double _dbData[];

  static const char* _names[];

  static const char* _units[];

  static const double _coords[];

  static const double _areaDir[];

};

#endif // spatialdata_spatialdb_simpledbquerydata3d_hh

// End of file
